// Boards
export const BOARDS_LOADING = 'BOARDS_LOADING'
export const BOARDS_LOADED = 'BOARDS_LOADED'

// Topics
export const TOPICS_LOADING = 'TOPICS_LOADING'
export const TOPICS_LOADED = 'TOPICS_LOADED'
export const TOPICS_CLEAR = 'TOPICS_CLEAR'

// Posts
export const POSTS_LOADING = 'POSTS_LOADING'
export const POSTS_LOADED = 'POSTS_LOADED'
export const POST_LOADING = 'POST_LOADING'
export const POST_LOADED = 'POST_LOADED'

// Load names
export const BOARD_NAME_LOADING = 'BOARD_NAME_LOADING'
export const BOARD_NAME_LOADED = 'BOARD_NAME_LOADED'

export const BOARD_TOPIC_NAMES_LOADING = 'BOARD_TOPIC_NAMES_LOADING'
export const BOARD_TOPIC_NAMES_LOADED = 'BOARD_TOPIC_NAMES_LOADED'

// Accounts
export const USER_LOADING = 'USER_LOADING'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_FAILED = 'USER_FAILED'
export const USER_LOADING_FAIELD = 'USER_LOADING_FAILED'
export const PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED'

// Profile
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_LOADED = 'PROFILE_LOADED'
export const PROFILE_PATCHED = 'PROFILE_PATCHED'

// Message System
export const ERROR_CREATE = 'ERROR_CREATE'
export const MESSAGE_CREATE = 'MESSAGE_CREATE'
// Clear messages & errors
export const ALERTS_CLEAR = 'ALERTS_CLEAR'

// Password Reset
export const TOKEN_CHECKING = 'TOKEN_CHECKING'
export const TOKEN_CHECKED = 'TOKEN_CHECKED'
export const TOKEN_FAILED = 'TOKEN_FAILED'